### ISSUE TITLE
Devicelister.exe not loading in latest version (1.0.4)

### ISSUE THREAD

**Issue by Buzzkill616** [briankendall/devreorder#54]
I downloaded v1.0.4 today and device lister was throwing an error, DirectX9 is installed. I downloaded v1.0.3 and device lister works just fine from that version so I am using that version of Devicelister.exe. Thanks for this it will be very helpful for my arcade cab.

**Comment by briankendall** [comment]
Can you copy / paste or take a screen shot of the error?

Make sure that DIDeviceInputId.dll is in the same folder as DeviceLister.exe otherwise it won't run.

**Comment by Buzzkill616** [comment]
![DeviceLister103](https://github.com/user-attachments/assets/36cd2c15-8eee-4b22-a547-3347f319fc1b)
![DeviceLister104](https://github.com/user-attachments/assets/0617befb-55ef-4424-8ecd-9c97eb0b4631)
/Downloads/devreorder/DeviceLister.exe

Error Details:
************** Exception Text **************
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at DeviceLister.DeviceListerForm.GetDeviceInstanceID(String input)
   at DeviceLister.DeviceListerForm.DeviceListerForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9179 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
DeviceLister
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/XXXX
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9157 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9176 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9157 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.DirectX.DirectInput
    Assembly Version: 1.0.2902.0
    Win32 Version: 5.04.00.2904
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.DirectX.DirectInput/1.0.2902.0__31bf3856ad364e35/Microsoft.DirectX.DirectInput.dll
----------------------------------------
Microsoft.DirectX
    Assembly Version: 1.0.2902.0
    Win32 Version: 5.04.00.2904
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.DirectX/1.0.2902.0__31bf3856ad364e35/Microsoft.DirectX.dll
----------------------------------------

**Comment by briankendall** [comment]
Which version of Windows are you running, and is it 32-bit, 64-bit, or ARM Windows?

**Comment by mchenier** [comment]
I think I had the same error. I am on Windows 10 and the I had the system wide 64bit dinput8.dll in place.
To make the DeviceLister.exe work I just had to copy the dinput8.dll 32bit in the directory of the executable and it worked.
